version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FaceDetection"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gd58zudv25f4"
s3_prefix = "FaceDetection"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["FaceDetectionFunction=194795991537.dkr.ecr.us-east-1.amazonaws.com/facedetectiond52b2c30/facedetectionfunctionbc7b2495repo"]
