version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gd58zudv25f4"
s3_prefix = "helloLambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
